# Generated by Django 3.2.4 on 2021-06-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('1', 'Urbana'), ('2', 'Rural')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Las Parroquias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barrio_Ciudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numViviendas', models.CharField(max_length=30)),
                ('numParques', models.CharField(choices=[('1', '1 Parque'), ('2', '2 Parques'), ('3', '3 Parques'), ('4', '4 Parques'), ('5', '5 Parques'), ('6', '6 Parques')], max_length=30)),
                ('numEdif', models.CharField(max_length=30)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Barrios / Ciudadelas',
                'ordering': ['nombre', 'parroquia'],
            },
        ),
    ]
