# Generated by Django 3.2.4 on 2021-06-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0002_alter_parroquia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
